### ISSUE TITLE
Tracking issue: Typst support

### ISSUE THREAD

**Issue by alexpovel** [alexpovel/srgn#147]
TODO:

- [ ] richer Typst support, WIP at https://github.com/alexpovel/srgn/tree/typst
- [ ] make it useful with type checking (`aspell`), for which the `text` node type seems most useful
- [ ] which requires piping into aspell, for which srgn currently doesn't have good support. Probably needs refactoring the crappy `apply` function:

    https://github.com/alexpovel/srgn/blob/9238fc161ceaf88dd754d71b4fb65393dcee964b/src/main.rs#L568
    
    so its output is something like (command run on commit https://github.com/alexpovel/srgn/commit/47be5f0ed8aab2afb2e9e473ea3eac9ed4607cf3)
    
    ```text
    [filename if not stdin];linenum;startcol;endcol: text
    ```
    
    e.g. (numbers made up)
    
    ```console
    $ cat tests/langs/typst/base.typ | c run -- -j --typ text --typ strings
    [...snip...]
    62;12;13: In case you missed it, there's a recording on
    62;58;62: "http://purview.edu/lts/2023-lee"
    ```
    
    i.e., it doesn't print non-`text` nodes such as `#link(`, as it currently does:
    
    
    <img width="1428" alt="image" src="https://github.com/user-attachments/assets/8a288042-3d4d-41bf-a844-6418b455f753">

cc @ju6ge

**Comment by alexpovel** [comment]
Kinda blocked, as I'd prefer not vendoring and only using grammars part of the [tree-sitter org](https://github.com/tree-sitter). Otherwise, it can get pretty painful with updates and keeping things in sync (see HCL support in srgn).

**Comment by lysogeny** [comment]
For spell checking I was wondering if it might be sufficient to strip out the markup, similar to what the TeX tool `detex` does, only making this print the selected nodes in some mode. The resulting file could then be piped into a user's favourite spellchecker and should, for that task, probably be good enough?

**Comment by alexpovel** [comment]
Thanks for your thoughts!

I had considered skipping the whole part about "if srgn is piped into something that is not a terminal, use machine-friendly/parseable output" and instead just offer JSON output. That's much more flexible, and (probably) easier to implement at the same time. It avoids work on my side (coming up with a parse-friendly format), but also allows full flexibility on the reading side of the pipe. It could look like `srgn --whatever | jq '.whatever' | spellcheck`. You would "only" need to massage the `jq` query, which is infinitely more powerful than what `srgn` could ever offer (and an LLM could probably write it very well for you). Let me know if you have any thoughts on that.

(work on srgn is currently slow, sorry!)

**Comment by ju6ge** [comment]
I am not opposed to json. Might very well be more flexible when transformed with jq. The blocker on my side ist that I have not found a spell checking tool gives me simple enough output that can be further processed easily. So no need to apologise for slow development.

**Comment by alexpovel** [comment]
There's now parseable/pipeable output formatting, done in #219 and released as part of #212 🙂 

Next step is for a tree-sitter Typst crate to become blessed and available: https://crates.io/search?q=tree-sitter-typst
